### ISSUE TITLE
Not able to upgrade our Bastion host to use the AL2023 OS via Deploy Linux Bastion Hosts into an existing VPC option in https://aws-ia.github.io/cfn-ps-linux-bastion/#_deployment_options 

### ISSUE THREAD

**Issue by TanyaShah4** [aws-ia/cfn-ps-linux-bastion#105]
I am looking to upgrade our Bastion host to use the AL2023 OS. There isnt currently an allowed value for AL2023 ARM in the aws cloudformation Bastion template. Can you please assist me in adding this option into the cloudformation stack?

**Comment by troy-ameigh** [comment]
We are currently working on this.
